/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3d_alone (https://sketchfab.com/3d_alone)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hipgig-e57e7d7b5c0744c4b24e21fe44567e38
title: Hipgig
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Drums({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Blender/Drums.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={0.3} position={[0,-16,0]} rotation={[0 , -5.5, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material-color={props.customColors.circulosDrum} geometry={nodes.Object_2.geometry} material={materials.blinn6SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert14SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert14SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert14SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert14SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/Drums.glb')
