import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Guitar({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Blender/guitar_model.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.chords.geometry}
        material={materials.chords}
        material-color={props.customColors.chords}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.face.geometry}
        material={materials.face}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_0.geometry}
        material={nodes.Mesh_0.material}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_3.geometry}
        material-color={props.customColors.body}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_10.geometry}
        material={materials.Material_10}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_11.geometry}
        material={materials.Material_11}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_12.geometry}
        material={materials.Material_12}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_13.geometry}
        material={materials.Material_13}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_14.geometry}
        material={materials.Material_14}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_15.geometry}
        material={materials.Material_15}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_16.geometry}
        material={materials.Material_16}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_17.geometry}
        material={materials.Material_17}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_18.geometry}
        material-color={"#B9B7BD"}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_20.geometry}
        material={materials.Material_20}
        material-color={props.customColors.body}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_4.geometry}
        material={materials.Material_4}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_5.geometry}
        material-color={"#B9B7BD"}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_6.geometry}
        material-color={"#B9B7BD"}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_7.geometry}
        material={materials.Material_7}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_8.geometry}
        material={materials.Material_8}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh_9.geometry}
        material={materials.Material_9}
        material-color={props.customColors.face}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.support.geometry}
        material={materials.body}
        material-color={props.customColors.body}
      />
    </group>
  );
}
