/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef , Suspense} from 'react'
import { useGLTF } from '@react-three/drei'

export default function Pianoo({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Blender/pianoo.glb')
  console.log(props)
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.bone} />
      <skinnedMesh material-color={props.customColors.Hinges} geometry={nodes.Hinges.geometry} material={materials.Hinges} skeleton={nodes.Hinges.skeleton} />
      <skinnedMesh material-color={props.customColors.Keys} geometry={nodes.Keys.geometry} material={nodes.Keys.materials} skeleton={nodes.Keys.skeleton} />
      <skinnedMesh material-color={props.customColors.Piano} geometry={nodes.Piano.geometry} material={nodes.Piano.material} skeleton={nodes.Piano.skeleton} />
      {/* <mesh geometry={nodes.Scene_1.geometry} material={materials['default']} scale={8} /> */}
    </group>
  )
}

useGLTF.preload('/pianoo.glb')
