/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DailyArt (https://sketchfab.com/D.art)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/violin-482f981a67f34f858fdb5e37fed61761
title: violin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Violin({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Blender/Violin.glb')
  return (
    <group ref={group} {...props} dispose={null} position={[-5 ,-18 ,6]} rotation={[0 , 1.7, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 21.02, 0]} scale={21.45}>
            <mesh material-color={props.customColors.the_stick} geometry={nodes.Object_6.geometry} material={materials.the_stick} />
            <mesh material-color={props.customColors.bodyViolin} geometry={nodes.Object_9.geometry} material={materials.xiaotiqin} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Violin.glb')

